# Generated by Django 5.0.6 on 2024-07-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_images/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_type',
            field=models.IntegerField(choices=[(1, 'Movie 1'), (2, 'Movie 2')], default=1),
            preserve_default=False,
        ),
    ]
