# Generated by Django 5.0.6 on 2024-07-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_image_movie_movie_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_type',
        ),
    ]
